// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZb8fCL3N-FO7wEKQoePXc5g2kDXYKJU',
    appId: '1:458951487671:web:e79795f9f650cbb0391d32',
    messagingSenderId: '458951487671',
    projectId: 'akanga-version',
    authDomain: 'akanga-version.firebaseapp.com',
    storageBucket: 'akanga-version.appspot.com',
    measurementId: 'G-X9BRWKBMW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIxwcB5bAP9Iq-pDs8XxZwPcrty5mF_b0',
    appId: '1:458951487671:android:98830b9f6e468a00391d32',
    messagingSenderId: '458951487671',
    projectId: 'akanga-version',
    storageBucket: 'akanga-version.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6lSWQohE3T6Ur-E766kX5bc8OHhSn91k',
    appId: '1:458951487671:ios:28bfe65b76e23019391d32',
    messagingSenderId: '458951487671',
    projectId: 'akanga-version',
    storageBucket: 'akanga-version.appspot.com',
    iosClientId: '458951487671-kb5154vnkua4kknqj2dbgcmng5olarv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.akangatuProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6lSWQohE3T6Ur-E766kX5bc8OHhSn91k',
    appId: '1:458951487671:ios:7f8847a10dfede92391d32',
    messagingSenderId: '458951487671',
    projectId: 'akanga-version',
    storageBucket: 'akanga-version.appspot.com',
    iosClientId: '458951487671-0e6928ufgrca7j5ej8k9784n8420ictg.apps.googleusercontent.com',
    iosBundleId: 'com.example.akangatuProject.RunnerTests',
  );
}
